[package]
name = "battler-wamprat-uri"
version = "0.5.0"
edition = "2024"
description = "Procedural macro for dynamically matching WAMP URIs."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket", "uri"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamprat/battler-wamprat-uri"

[dependencies]
thiserror = { workspace = true }

battler-wamp = { workspace = true }
battler-wamp-uri = { workspace = true }
battler-wamprat-uri-proc-macro = "0.5.0"

[dev-dependencies]
assert_matches = { workspace = true }
regex = { workspace = true }
