[package]
name = "battler-wamprat-message-proc-macro"
version = "0.1.2"
edition = "2024"
description = "Procedural macro for sending structs over WAMP messages."
authors = ["Jackson Nestelroad <jackson@nestelroad.com>"]
keywords = ["wamp", "websocket", "message"]
license = "MIT"
repository = "https://github.com/jackson-nestelroad/battler/tree/main/battler-wamprat/battler-wamprat-message/battler-wamprat-message-proc-macro"

[lib]
proc-macro = true

[dependencies]
itertools = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
pretty_assertions = { workspace = true }

battler-wamp-values = { workspace = true }

battler-wamprat-message = { path = ".." }
